### ISSUE TITLE
Add flat config support (ESlint 9.0.0)

### ISSUE THREAD

**Issue by hugoattal** [hugoattal/eslint-plugin-sort-keys-custom-order#4]
Requires this typescript-eslint update:
- https://github.com/typescript-eslint/typescript-eslint/issues/8211

Specifically, RuleTester seems not compatible with flat config for now.
```
Serialized Error: { messageTemplate: 'eslintrc-incompat', messageData: { key: 'parser' } }
Caused by: Error: This appears to be in eslintrc format rather than flat config format.
```

**Comment by hugoattal** [comment]
Requires FlatRuleTester: 
- https://github.com/typescript-eslint/typescript-eslint/issues/9017

**Comment by 1qh** [comment]
Thank you for your awesome project. I'm looking forward to seeing this plugin in my flat config. Keep up the good work!

**Comment by hugoattal** [comment]
Done!

```ts
import tseslint from "typescript-eslint";
import sortKeysCustomOrder from "eslint-plugin-sort-keys-custom-order";

export default tseslint.config(
    /* ... */
    sortKeysCustomOrder.configs["flat/recommended"],
    /* ... */
);
```

**Comment by haisonle001** [comment]
awesome, thanks a lot

**Comment by 1qh** [comment]
awesome, thanks a lot
